### ISSUE TITLE
Unable to open logs file

### ISSUE THREAD

**Issue by silverandrew** [ejmurra/salaryGuide#8]
I get the following error when I try running gulp dev:\

`uncaughtException: ENOENT, open '../salaryGuide/logs/info.log'`

The issue is resolved if I create a logs/ directory in the root directory. So I'm guessing add this as part of the install process somehow?

**Comment by ejmurra** [comment]
Fixed with commit 5351d3638d405977922fd3fa312a6b54f048cd18
