### ISSUE TITLE
Could not connect to postgres

### ISSUE THREAD

**Issue by silverandrew** [ejmurra/salaryGuide#9]
After running gulp dev, opening my browser and clicking on "Start Searching", I get the following error:

{"name":"error","length":95,"severity":"FATAL","code":"28P01","file":"auth.c","line":"304","routine":"auth_failed"},"level":"error","message":"could not connect to postgres","timestamp":"2016-02-21T16:28:30.988Z"}

The postgres database loads fine for me if I do psql salarydata , so I'm not sure if there are some authentication settings I need to set up somewhere.

I've tried editing the postgres configuration file to allow localhost connections via password, and edit auth.txt to the format suggested, with no change.

**Comment by ejmurra** [comment]
See previously closed issue #7 for info on setting up the auth module to connect to the db. The connection string is in the format `postgres://USERNAME:PASSWORD@localhost/salaryData`. Update USERNAME and PASSWORD to be your actual username and password for connecting to the database. For more info on how the pg module works, consult the documentation [here](https://github.com/brianc/node-postgres/wiki/pg).
